export type Person = {
  id: number;
  name: string;
  age: number;
  email: string;
  phone: string;
  city: string;
  state: string;
  country: string;
  zipcode: string;
  occupation: string;
};

export const data = [
  {
    id: 1,
    name: 'John Doe',
    age: 30,
    email: 'johndoe@example.com',
    phone: '123-456-7890',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zipcode: '10001',
    occupation: 'Software Engineer',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 25,
    email: 'janesmith@example.com',
    phone: '987-654-3210',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    zipcode: '90001',
    occupation: 'Data Analyst',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    age: 40,
    email: 'bobjohnson@example.com',
    phone: '555-555-5555',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    zipcode: '60601',
    occupation: 'Marketing Manager',
  },
  {
    id: 4,
    name: 'Emily Jones',
    age: 35,
    email: 'emilyjones@example.com',
    phone: '555-123-4567',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    zipcode: '77002',
    occupation: 'Financial Analyst',
  },
  {
    id: 5,
    name: 'David Lee',
    age: 28,
    email: 'davidlee@example.com',
    phone: '555-987-6543',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    zipcode: '94102',
    occupation: 'Product Manager',
  },
  {
    id: 6,
    name: 'Sarah Kim',
    age: 33,
    email: 'sarahkim@example.com',
    phone: '555-555-1234',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    zipcode: '98101',
    occupation: 'Human Resources Manager',
  },
  {
    id: 7,
    name: 'Mike Davis',
    age: 45,
    email: 'mikedavis@example.com',
    phone: '555-123-7890',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    zipcode: '02108',
    occupation: 'Sales Director',
  },
  {
    id: 8,
    name: 'Lisa Chen',
    age: 27,
    email: 'lisachen@example.com',
    phone: '555-789-1234',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    zipcode: '33101',
    occupation: 'Software Developer',
  },
  {
    id: 9,
    name: 'Alice',
    age: 25,
    email: 'alice@example.com',
    phone: '123-456-7890',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    zipcode: '94107',
    occupation: 'Data Scientist',
  },
  {
    id: 10,
    name: 'Bob',
    age: 35,
    email: 'bob@example.com',
    phone: '555-555-8888',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zipcode: '10001',
    occupation: 'Marketing Manager',
  },
  {
    id: 1,
    name: 'John Doe',
    age: 30,
    email: 'johndoe@example.com',
    phone: '123-456-7890',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zipcode: '10001',
    occupation: 'Software Engineer',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 25,
    email: 'janesmith@example.com',
    phone: '987-654-3210',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    zipcode: '90001',
    occupation: 'Data Analyst',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    age: 40,
    email: 'bobjohnson@example.com',
    phone: '555-555-5555',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    zipcode: '60601',
    occupation: 'Marketing Manager',
  },
  {
    id: 4,
    name: 'Emily Jones',
    age: 35,
    email: 'emilyjones@example.com',
    phone: '555-123-4567',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    zipcode: '77002',
    occupation: 'Financial Analyst',
  },
  {
    id: 5,
    name: 'David Lee',
    age: 28,
    email: 'davidlee@example.com',
    phone: '555-987-6543',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    zipcode: '94102',
    occupation: 'Product Manager',
  },
  {
    id: 6,
    name: 'Sarah Kim',
    age: 33,
    email: 'sarahkim@example.com',
    phone: '555-555-1234',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    zipcode: '98101',
    occupation: 'Human Resources Manager',
  },
  {
    id: 7,
    name: 'Mike Davis',
    age: 45,
    email: 'mikedavis@example.com',
    phone: '555-123-7890',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    zipcode: '02108',
    occupation: 'Sales Director',
  },
  {
    id: 8,
    name: 'Lisa Chen',
    age: 27,
    email: 'lisachen@example.com',
    phone: '555-789-1234',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    zipcode: '33101',
    occupation: 'Software Developer',
  },
  {
    id: 9,
    name: 'Alice',
    age: 25,
    email: 'alice@example.com',
    phone: '123-456-7890',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    zipcode: '94107',
    occupation: 'Data Scientist',
  },
  {
    id: 20,
    name: 'Bob',
    age: 35,
    email: 'bob@example.com',
    phone: '555-555-8888',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zipcode: '10001',
    occupation: 'Marketing Manager',
  },
];
